name: GLIBChecker

on:
  - push
  - pull_request

jobs:
  build:
    name: Check compilation and execute on itself
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile using CMake
        timeout-minutes: 2
        run: |
          mkdir build
          cd build
          cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          cd ..

      - name: Execute the program
        timeout-minutes: 2
        run: ./build/glib_checker ./build/glib_checker
